input           = "crypto_logger/90d_1h_sample/solana_eur.csv"

sample_hours    = 1

initial_cash    = 10000
buy_fraction    = 0.5

enable_crossovers           = true
atr_enabled                 = false
regime_enabled              = false
enable_bias_only            = false
require_price_confirmation  = true
require_trend_filter        = true
sma_short_window            = 30
sma_long_window             = 60
breakout_lookback           = 3
