input           = "crypto_logger/90d_1h_sample/solana_eur.csv"
sample_hours    = 1

initial_cash    = 10000

min_lookback                = 3
max_lookback                = 10
min_pullback_pct            = 0.001
max_pullback_pct            = 0.01

max_buy_sell_fraction       = 0.5
buy_sell_frac_steps         = 10
